nodeLinker: node-modules

# Allow each package to have its own node_modules
# so that they may have different dependency versions
# Currently used for:
# - web-ui uses next@^14 
# - data-api (through keystone.js) depends on next@^13.4
# nmHoistingLimits: workspaces
